- name: "Create radicale directory"
  file:
    path: "{{ radicale_home }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"

- name: "Install radicale"
  pip:
    name: "radicale[bcrypt]"
    version: "3.1.8"
    state: present
    executable: pip3
    extra_args: --break-system-packages

- name: "Create radicale config directory"
  file:
    path: /etc/radicale
    state: directory

- name: "Render radicale config file"
  template:
    src: config.j2
    dest: /etc/radicale/config
    owner: "{{ user }}"
    group: "{{ group }}"
  notify:
    - start radicale

- name: "Copy radicale additional config files"
  copy:
    src: "{{ item }}.conf"
    dest: "/etc/radicale/{{ item }}.conf"
    owner: "{{ user }}"
    group: "{{ group }}"
  loop:
    - permissions

- name: "Configure radicale admin account"
  htpasswd:
    path: /etc/radicale/users.htpasswd
    state: present
    username: "{{ radicale_admin_username }}"
    password: "{{ radicale_admin_password }}"
    crypt_scheme: bcrypt
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0640

- name: "Configure radicale user account"
  htpasswd:
    path: /etc/radicale/users.htpasswd
    state: present
    username: "{{ radicale_username }}"
    password: "{{ radicale_password }}"
    crypt_scheme: bcrypt
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0640

- name: "Create systemd service for radicale"
  template:
    src: radicale-unit.conf.j2
    dest: "{{ user_systemd_dir }}/radicale.service"
  notify:
    - start radicale

- name: "Copy radicale sites-available nginx conf"
  template:
    src: radicale.conf.j2
    dest: /etc/nginx/sites-available/radicale.conf
    owner: root
    group: root
  notify: "reload nginx"

- name: "Link radicale sites-enabled nginx conf"
  file:
    src: /etc/nginx/sites-available/radicale.conf
    dest: /etc/nginx/sites-enabled/radicale.conf
    state: link
  notify: "reload nginx"
