- name: Create the /mnt/data directory
  file:
    dest: /mnt/data
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"

- name: "Mount external USB disk as extra storage"
  lineinfile:
    path: /etc/fstab
    line: "UUID=3bcb0db3-8e65-4790-81c3-23547c8157c1 /mnt/data ext4 defaults,noatime,uid={{ user_uid }} 0 2"
    regexp: "/mnt/data"
    state: present
