- name: "Create backup directories"
  file:
    path: "/home/{{ user }}/backups/{{ item }}"
    state: directory
  become: yes
  become_user: "{{ user }}"
  loop:
    - sophro

- name: "Specificy ssh port for synology NAS"
  template:
    src: ssh_config.j2
    dest: "{{ user_home }}/.ssh/config"
    owner: "{{ user }}"
    group: "{{ group }}"

- name: "Schedule sophro backups"
  cron:
    name: "backup sophro"
    minute: "0"
    hour: "0"
    job: >
      /usr/local/bin/dd-cron-event
      "Backup sophro web files"
      "rsync --rsync-path=/usr/bin/rsync -r --delete {{ user_home }}/backups/sophro syno:{{ syno_user_home }}/backups/"
    user: "{{ user }}"

- name: "Schedule the backup of the wallabag database"
  cron:
    name: "backup wallabag db"
    minute: "0"
    hour: "0"
    job: >
      /usr/local/bin/dd-cron-event
      "Backup wallabag db"
      "sudo cp {{ user_home }}/wallabag/data/db/wallabag.sqlite /tmp/wallabag.sqlite && {{ syno_rsync }} /tmp/wallabag.sqlite syno:{{ syno_user_home }}/backups/wallabag/wallabag.sqlite && rm /tmp/wallabag.sqlite"
    user: "{{ user }}"

- name: "Schedule the backup of the calibre metadata database"
  cron:
    name: "backup calibre db"
    minute: "0"
    hour: "0"
    job: >
      /usr/local/bin/dd-cron-event
      "Backup calibre metadata db"
      "{{ syno_rsync }} -r {{ user_home }}/calibre/books/metadata.db syno:{{ syno_user_home }}/backups/calibre/metadata.db"
    user: "{{ user }}"

- name: "Schedule the backup of the calibre app database"
  cron:
    name: "backup calibre app db"
    minute: "0"
    hour: "0"
    job: >
      /usr/local/bin/dd-cron-event
      "Backup calibre db"
      "{{ syno_rsync }} -r {{ user_home }}/calibre/config/app.db syno:{{ syno_user_home }}/backups/calibre/app.db"
    user: "{{ user }}"

- name: "Schedule the backup of the isso database"
  cron:
    name: "backup isso db"
    minute: "0"
    hour: "0"
    job: >
      /usr/local/bin/dd-cron-event
      "Backup isso db"
      "{{ syno_rsync }} -r {{ isso_home }}/db/comments.db syno:{{ syno_user_home }}/backups/isso/comments.db"
    user: "{{ user }}"

- name: "Schedule the backup of radicale files"
  cron:
    name: "backup radicale files"
    minute: "0"
    hour: "0"
    job: >
      /usr/local/bin/dd-cron-event
      "Backup radicale files"
      "{{ syno_rsync }} -r {{ user_home }}/radicale syno:{{ syno_user_home }}/backups/radicale"
    user: "{{ user }}"

- name: "Schedule paperless backups"
  cron:
    name: "backup paperless"
    minute: "0"
    hour: "0"
    job: >
      /usr/local/bin/dd-cron-event
      "Backup paperless"
      "{{ syno_rsync }} -r {{ paperless_home }} syno:{{ syno_user_home }}/backups/paperless"
    user: "{{ user }}"

- name: "Schedule fathom backups"
  cron:
    name: "backup fathom DB"
    minute: "0"
    hour: "0"
    job: >
      /usr/local/bin/dd-cron-event
      "Backup fathom db"
      "{{ syno_rsync }} {{ fathom_home }}/fathom.db syno:{{ syno_user_home }}/backups/fathom"
    user: "{{ user }}"

- name: "Schedule silverbullet backups"
  cron:
    name: "backup silverbullet files"
    minute: "0"
    hour: "0"
    job: >
      /usr/local/bin/dd-cron-event
      "Backup silverbullet files"
      "{{ syno_rsync }} -r --delete {{ silverbullet_space }} syno:{{ syno_user_home }}/backups/silverbullet/"
    user: "{{ user }}"

- name: "Schedule the backup of the yarr database"
  cron:
    name: "backup yarr db"
    minute: "0"
    hour: "0"
    job: >
      /usr/local/bin/dd-cron-event
      "Backup yarr db"
      "{{ syno_rsync }} -r {{ yarr_home }}/yarr.db syno:{{ syno_user_home }}/backups/yarr/yarr.db"
    user: "{{ user }}"

- name: "Schedule the backup of the authelia database"
  cron:
    name: "backup authelia db"
    minute: "0"
    hour: "0"
    job: >
      /usr/local/bin/dd-cron-event
      "Backup authelia db"
      "{{ syno_rsync }} -r {{ authelia_home }}/authelia.db syno:{{ syno_user_home }}/backups/authelia/authelia.db"
    user: "{{ user }}"

- name: "Schedule the backup of martial's website"
  cron:
    name: "backup martial's website"
    minute: "0"
    hour: "0"
    job: >
      /usr/local/bin/dd-cron-event
      "Backup martial's website"
      "{{ syno_rsync }} -r {{ martial_web_dir }}/ syno:{{ syno_user_home }}/backups/martial/"
    user: "{{ user }}"
