- name: "Create backup directories"
  file:
    path: "/home/{{ user }}/backups/{{ item }}"
    state: directory
  become: yes
  become_user: "{{ user }}"
  loop:
    - sophro

- name: "Specificy ssh port for synology NAS"
  template:
    src: ssh_config.j2
    dest: "{{ user_home }}/.ssh/config"
    owner: "{{ user }}"
    group: "{{ group }}"

- name: "Schedule sophro backups"
  cron:
    name: "backup sophro"
    minute: "0"
    hour: "0"
    job: >
      /usr/local/bin/dd-cron-event
      "Backup sophro web files"
      "rsync --rsync-path=/usr/bin/rsync -r --delete {{ user_home }}/backups/sophro syno:~/backups/"
    user: "{{ user }}"

- name: "Schedule the backup of the calibre space"
  cron:
    name: "backup calibre"
    minute: "0"
    hour: "0"
    job: >
      /usr/local/bin/dd-cron-event
      "Backup calibre"
      "{{ syno_rsync }} -r {{ user_home }}/calibre syno:~/backups/"
    user: "{{ user }}"

- name: "Schedule the backup of the isso database"
  cron:
    name: "backup isso db"
    minute: "0"
    hour: "0"
    job: >
      /usr/local/bin/dd-cron-event
      "Backup isso db"
      "{{ syno_rsync }} -r {{ isso_home }} syno:~/backups/"
    user: "{{ user }}"

- name: "Schedule the backup of radicale files"
  cron:
    name: "backup radicale files"
    minute: "0"
    hour: "0"
    job: >
      /usr/local/bin/dd-cron-event
      "Backup radicale files"
      "{{ syno_rsync }} -r {{ user_home }}/radicale syno:~/backups/"
    user: "{{ user }}"

- name: "Schedule paperless backups"
  cron:
    name: "backup paperless"
    minute: "0"
    hour: "0"
    job: >
      /usr/local/bin/dd-cron-event
      "Backup paperless"
      "{{ syno_rsync }} -r {{ paperless_home }} syno:~/backups/"
    user: "{{ user }}"

- name: "Schedule silverbullet backups"
  cron:
    name: "backup silverbullet files"
    minute: "0"
    hour: "0"
    job: >
      /usr/local/bin/dd-cron-event
      "Backup silverbullet files"
      "{{ syno_rsync }} -r --delete {{ silverbullet_home }} syno:~/backups/"
    user: "{{ user }}"

- name: "Schedule the backup of the yarr database"
  cron:
    name: "backup yarr db"
    minute: "0"
    hour: "0"
    job: >
      /usr/local/bin/dd-cron-event
      "Backup yarr db"
      "{{ syno_rsync }} -r {{ yarr_home }} syno:~/backups"
    user: "{{ user }}"

- name: "Schedule the backup of the authelia database"
  cron:
    name: "backup authelia db"
    minute: "0"
    hour: "0"
    job: >
      /usr/local/bin/dd-cron-event
      "Backup authelia db"
      "{{ syno_rsync }} -r {{ authelia_home }} syno:~/backups/"
    user: "{{ user }}"

- name: "Schedule the backup of martial's website"
  cron:
    name: "backup martial's website"
    minute: "0"
    hour: "0"
    job: >
      /usr/local/bin/dd-cron-event
      "Backup martial's website"
      "{{ syno_rsync }} -r {{ martial_web_dir }}/ syno:~/backups/martial/"
    user: "{{ user }}"

- name: "Schedule foundry data backup"
  cron:
    name: "backup foundry data"
    minute: "0"
    hour: "4"
    job: >
      /usr/local/bin/dd-cron-event
      "Foundry data backup"
      "{{ syno_rsync }} -r {{ foundry_home }} --exclude container_cache syno:~/backups/"
    user: "{{ user }}"

- name: "Backup sonarr"
  cron:
    name: "Backup sonarr"
    minute: "0"
    hour: "1"
    job: "{{ syno_rsync }} -r {{ sonarr_home }} syno:~/backups/"
    user: "{{ user }}"

- name: "Backup bazarr"
  cron:
    name: "Backup bazarr"
    minute: "0"
    hour: "1"
    job: "{{ syno_rsync }} -r {{ bazarr_home }} syno:~/backups/"
    user: "{{ user }}"

- name: "Backup radarr"
  cron:
    name: "Backup radarr"
    minute: "0"
    hour: "1"
    job: "{{ syno_rsync }} -r {{ radarr_home }} syno:~/backups/"
    user: "{{ user }}"

- name: "Backup jackett"
  cron:
    name: "Backup jackett"
    minute: "0"
    hour: "1"
    job: "{{ syno_rsync }} -r {{ jackett_home }} syno:~/backups/"
    user: "{{ user }}"

- name: "Backup personal page space"
  cron:
    name: "Backup personal page space"
    minute: "0"
    hour: "5"
    job: "{{ syno_rsync }} -r --delete {{ page_web_dir }} syno:~/backups/"
    user: "{{ user }}"

- name: "Backup yarr OPML"
  cron:
    name: "backup yarr opml"
    minute: "0"
    hour: "2"
    job: "curl -s http://{{ yarr_host }}:{{ yarr_port }}/opml/export > {{ yarr_home }}/yarr.opml"
    user: "{{ user }}"
