- name: "Update and upgrade packages"
  apt:
    update_cache: yes
    upgrade: dist

- name: "Install packages"
  apt:
    name:
    - htop
    - python-pip
    - vim
    state: present

- name: "Remove unwanted packages"
  apt:
    name:
    - lighttpd
    state: absent

- name: "Install python packages"
  pip:
    name:
    - pip
    - passlib
    - setuptools
    state: latest

- name: "Setup motd"
  copy:
    src: motd
    dest: /etc/motd

- name: "Setup profile"
  copy:
    src: profile
    dest: "{{ user_home }}/.profile"
    owner: "{{ user }}"

- name: 'Set hostname'
  hostname:
    name: "{{ hostname }}"

- name: "Make hostname resolvable"
  lineinfile:
    path: /etc/hosts
    regexp: '127.0.0.1 localhost'
    line: "127.0.0.1 localhost {{ hostname }}"
    state: present

- name: "Create /opt directory"
  file:
    path: "{{ opt_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"

- name: "Setup user authorized keys"
  template:
    src: authorized_keys.j2
    dest: "{{ user_home }}/.ssh/authorized_keys"
  become: yes
  become_user: "{{ user }}"
