- name: "Create the sonarr home directory"
  file:
    path: "{{ sonarr_home }}"
    state: directory
    owner: debian-transmission
    group: debian-transmission

- name: "Run the sonarr container"
  include_role:
    name: mhutter.docker-systemd-service
  vars:
    container_name: sonarr
    # we're blocked on that tag, cf https://info.linuxserver.io/issues/2022-08-02-sonarr/
    container_image: lscr.io/linuxserver/sonarr:develop-3.0.8.1540-ls294
    container_ports:
      - "0.0.0.0:{{ sonarr_port }}:{{ sonarr_port }}/tcp"
    container_env:
      PUID: "{{ transmission_uid | quote }}"
      PGID: "{{ transmission_gid | quote }}"
      TZ: "Europe/Paris"
    container_volumes:
      - "{{ sonarr_home }}:/config"
      - "{{ sonarr_series_dir }}:/tv"
      - "{{ transmission_download_dir }}:/downloads"
    container_args: "--cpus 1 --memory 150m"
    service_systemd_unit_options:
      After: "docker.service mnt-nas-series.mount mnt-nas-transmission.mount"
      Requires: "docker.service mnt-nas-series.mount mnt-nas-transmission.mount"

- name: "Backup the sonarr database"
  cron:
    name: "Backup the sonarr database"
    minute: "0"
    hour: "1"
    job: "{{ syno_rsync }} {{ sonarr_home }}/sonarr.db {{ user }}@{{ syno_internal_ip }}:~/backups/sonarr/sonarr.db"
    user: "{{ user }}"
