- name: "Create the project directory"
  file:
    path: "{{ user_home }}/notion"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"

- name: "Render the script"
  template:
    src: report_cesu.py.j2
    dest: "{{ user_home }}/notion/report_cesu.py"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: "0755"
