- name: "Setup user authorized keys"
  template:
    src: authorized_keys.j2
    dest: "{{ user_home }}/.ssh/authorized_keys"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: "0600"

- name: "Only authorize select users to ssh"
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "AllowUsers {{ user }}"
    regexp: "AllowUsers"
    state: present
  notify:
    - restart ssh

- name: Enable the ssh service
  systemd:
    name: sshd
    enabled: yes
    masked: no
