---
- name: "start pastebin"
  become: yes
  become_user: "{{ user }}"
  service:
    name: pastebin
    state: started
    enabled: yes
    user: yes
    daemon_reload: yes
  environment:
    XDG_RUNTIME_DIR: "{{ user_xdg_runtime_dir }}"
