- name: "Create the radarr home config"
  file:
    path: "{{ radarr_home }}"
    state: directory
    owner: debian-transmission
    group: debian-transmission

- name: "Run the radarr container"
  include_role:
    name: mhutter.docker-systemd-service
  vars:
    container_name: radarr
    container_image: lscr.io/linuxserver/radarr:latest
    container_docker_pull: yes
    container_ports:
      - "{{ ansible_default_ipv4.address }}:{{ radarr_port }}:{{ radarr_port }}/tcp"
    container_env:
      PUID: "{{ transmission_uid | quote }}"
      PGID: "{{ transmission_gid | quote }}"
      TZ: "Europe/Paris"
    container_volumes:
      - "{{ radarr_home }}:/config"
      - "{{ radarr_films_dir }}:/tv"
      - "{{ transmission_download_dir }}:/downloads"

- name: "Backup the radarr database"
  cron:
    name: "Backup the radarr database"
    minute: "0"
    hour: "1"
    job: "{{ syno_rsync }} {{ radarr_home }}/radarr.db {{ user }}@{{ syno_internal_ip }}:~/backups/radarr/radarr.db"
    user: "{{ user }}"
