- name: "Create the bazarr home config"
  file:
    path: "{{ bazarr_home }}"
    state: directory
    owner: debian-transmission
    group: debian-transmission

- name: "Run the bazarr container"
  include_role:
    name: mhutter.docker-systemd-service
  vars:
    container_name: bazarr
    container_image: lscr.io/linuxserver/bazarr:latest
    container_docker_pull: yes
    container_ports:
      - "{{ ansible_default_ipv4.address }}:{{ bazarr_port }}:{{ bazarr_port }}/tcp"
    container_env:
      PUID: "{{ transmission_uid | quote }}"
      PGID: "{{ transmission_gid | quote }}"
      TZ: "Europe/Paris"
    container_volumes:
      - "{{ bazarr_home }}:/config"
      - "{{ sonarr_series_dir }}:/tv"
      - "{{ transmission_download_dir }}:/downloads"

- name: "Backup the bazarr database"
  cron:
    name: "Backup the bazarr database"
    minute: "0"
    hour: "1"
    job: "{{ syno_rsync }} {{ bazarr_home }}/db/bazarr.db {{ user }}@{{ syno_internal_ip }}:~/backups/bazarr/bazarr.db"
    user: "{{ user }}"
