#!/usr/bin/env python3
"""
Syntaxic sugar around the Makefile, for a better UX.

Example: ./deploy homer transmission --to pi
"""

import argparse
import subprocess


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("tags", nargs="+", help="The ansible tags to deploy")
    parser.add_argument("--to", help="The host to deploy to")
    return parser.parse_args()


def main():
    args = parse_args()
    cmd = ["make", f"playbook-{args.to}", f'tags={",".join(args.tags)}']
    print(" ".join(cmd))
    subprocess.check_call(cmd)


if __name__ == "__main__":
    main()
