---
- name: "Install cssmin"
  pip:
    name: cssmin
    state: present
    extra_args: --break-system-packages

- name: "Create page git bare repo"
  command: "git init --bare {{ page_repo }}"
  args:
    creates: "{{ page_repo }}"

- name: "Change owner of the repo"
  command: "chown -R {{ git_user }}:{{ git_group }} {{ page_repo }}"

- name: "Change user/group of the page git repo"
  file:
    path: "{{ page_repo }}"
    owner: "{{ git_user }}"
    group: "{{ git_group }}"

- name: "Deploy git post receive hook"
  template:
    src: git-post-receive-hook.j2
    dest: "{{ page_repo }}/hooks/post-receive"
    owner: "{{ git_user }}"
    group: "{{ git_group }}"
    mode: 0755

- name: "Create page www directory"
  file:
    path: "{{ page_web_dir }}"
    state: directory
    owner: "{{ web_user }}"
    group: "{{ git_group }}"
    mode: 0775

- name: "Create additional www directory"
  file:
    path: "{{ page_web_dir }}/{{ item }}"
    state: directory
    owner: "{{ web_user }}"
    group: users
    mode: 0775
  loop:
    - public
    - slides

- name: "Copy page sites-available nginx conf"
  template:
    src: page.conf.j2
    dest: /etc/nginx/sites-available/page.conf
    owner: root
    group: root
  notify: "reload nginx"

- name: "Link page sites-enabled nginx conf"
  file:
    src: /etc/nginx/sites-available/page.conf
    dest: /etc/nginx/sites-enabled/page.conf
    state: link
  notify: "reload nginx"

- name: "Redeploy personal page after each birthday"
  cron:
    name: "redeploy personal page after each birthday"
    minute: "0"
    hour: "1"
    day: "4"
    month: "11"
    job: >
      /usr/local/bin/dd-cron-event
      "Redeploy personal page after each birthday"
      "{{ page_repo }}/hooks/post-receive"
    user: "{{ git_user }}"

- name: "Run the ypsilon14 docker container"
  docker_container:
    name: ypsilon14
    image: ypsilon14
    state: started
    pull: no
    published_ports:
      - "127.0.0.1:{{ ypsilon14_port }}:80"
    restart_policy: unless-stopped
