---
- name: "Install cssmin"
  pip:
    name: cssmin
    state: present

- name: "Create page git bare repo"
  command: "git init --bare {{ page_repo }}"
  args:
    creates: "{{ page_repo }}"

- name: "Change owner of the repo"
  command: "chown -R {{ git_user }}:{{ git_group }} {{ page_repo }}"

- name: "Change user/group of the page git repo"
  file:
    path: "{{ page_repo }}"
    owner: "{{ git_user }}"
    group: "{{ git_group }}"

- name: "Deploy git post receive hook"
  template:
    src: git-post-receive-hook.j2
    dest: "{{ page_repo }}/hooks/post-receive"
    owner: "{{ git_user }}"
    group: "{{ git_group }}"
    mode: 0755

- name: "Create page www directory"
  file:
    path: "{{ page_web_dir }}"
    state: directory
    owner: "{{ web_user }}"
    group: "{{ git_group }}"
    mode: 0775

- name: "Create additional www directory"
  file:
    path: "{{ page_web_dir }}/{{ item }}"
    state: directory
    owner: "{{ web_user }}"
    group: users
    mode: 0775
  loop:
    - public
    - slides

- name: "Copy page sites-available nginx conf"
  template:
    src: page.conf.j2
    dest: /etc/nginx/sites-available/page.conf
    owner: root
    group: root
  notify: "reload nginx"

- name: "Link page sites-enabled nginx conf"
  file:
    src: /etc/nginx/sites-available/page.conf
    dest: /etc/nginx/sites-enabled/page.conf
    state: link
  notify: "reload nginx"

- name: "Redeploy personal page after each birthday"
  cron:
    name: "redeploy personal page after each birthday"
    minute: "0"
    hour: "1"
    day: "4"
    month: "11"
    job: >
      /usr/local/bin/dd-cron-event
      "Redeploy personal page after each birthday"
      "{{ page_repo }}/hooks/post-receive"
    user: "{{ git_user }}"

- name: "Install htmlq"
  unarchive:
    src: https://github.com/mgdm/htmlq/releases/download/v0.4.0/htmlq-x86_64-linux.tar.gz
    dest: /usr/local/bin
    remote_src: yes

- name: "Install rssgen"
  copy:
    src: rssgen.py
    dest: /usr/local/bin/rssgen
    group: git
    mode: 0775

- name: "Install rss_scrape_wmfjobs"
  copy:
    src: rss_scrape_wmfjobs.py
    dest: /usr/local/bin/rss_scrape_wmfjobs
    group: git
    mode: 0775

- name: "Install rss_scrape_sharpmaps"
  copy:
    src: rss_scrape_sharpmaps.py
    dest: /usr/local/bin/rss_scrape_sharpmaps
    group: git
    mode: 0775

- name: "Schedule WMF jobs rss export"
  cron:
    name: "wmf jobs rss"
    minute: "0"
    hour: "4"
    job: >
      curl -s "https://job-boards.greenhouse.io/wikimedia\?departments%5B%5D\=91046" |
      /usr/local/bin/rss_scrape_wmfjobs |
      rssgen --title 'WMF Jobs' --link '' --description 'P/T jobs at the WMF' > {{ page_web_dir }}/public/wmfjobs.rss
    user: git

- name: "Schedule sharpamps rss export"
  cron:
    name: "sharpmaps jobs rss"
    minute: "0"
    hour: "4"
    job: >
      curl -s "https://sharpmaps.com/" |
      /usr/local/bin/rss_scrape_sharpmaps |
      rssgen --title 'Sharpmaps' --link 'https://sharpmaps.com' --description 'Generate beautiful maps' > {{ page_web_dir }}/public/sharpmaps.rss
    user: git
