- name: Create the tuya directory
  file:
    path: "{{ user_home }}/tuya"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"

- name: "Install python packages"
  pip:
    name:
    - datadog
    - tinytuya
    state: present
    virtualenv: "{{ user_home }}/tuya/.env"
    virtualenv_python: python3

- name: "Render the metric exporter script"
  template:
    src: exporter.py.j2
    dest: "{{ user_home }}/tuya/exporter.py"

- name: "Export outlet metrics every minute"
  cron:
    name: "Export outlet metrics every minute"
    minute: "*"
    hour: "*"
    job: "cd {{ user_home }}/tuya && {{ user_home }}/tuya/.env/bin/python exporter.py"
    user: "{{ user }}"
