- name: "Create the silverbullet directory"
  file:
    path: "{{ silverbullet_home }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group  }}"

- name: "Create the silverbullet space directory"
  file:
    path: "{{ silverbullet_space }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group  }}"

- name: "Start the silverbullet container"
  docker_container:
    name: silverbullet
    image: "zefhemel/silverbullet:{{ silverbullet_version }}"
    state: started
    pull: yes
    published_ports:
      - "{{ silverbullet_host }}:{{ silverbullet_port }}:3000"
    restart_policy: unless-stopped
    volumes:
      - "{{ silverbullet_space }}:/space"

- name: "Copy silverbullet sites-available nginx conf"
  template:
    src: silverbullet.conf.j2
    dest: /etc/nginx/sites-available/silverbullet.conf
    owner: root
    group: root
  notify: "reload nginx"

- name: "Link silverbullet sites-enabled nginx conf"
  file:
    src: /etc/nginx/sites-available/silverbullet.conf
    dest: /etc/nginx/sites-enabled/silverbullet.conf
    state: link
  notify: "reload nginx"
