- name: Install the docker package
  apt:
    name: docker.io
    state: present
  when: ansible_os_family == "Debian" and ansible_lsb['id'] != 'Raspbian'

- name: Download the docker convenience installation script
  get_url:
    url: https://get.docker.com
    dest: /tmp/get-docker.sh
    mode: '0744'
  when: ansible_os_family == "Debian" and ansible_lsb['id'] == 'Raspbian'

- name: Run the docker convenience installation script
  command: /tmp/get-docker.sh
  when: ansible_os_family == "Debian" and ansible_lsb['id'] == 'Raspbian'
  ignore_errors: yes

- name: "Add user to the docker group"
  user:
    name: "{{ user }}"
    uid: "{{ user_uid }}"
    groups: "{{ group }},sudo,docker"
    append: yes
    state: present

- name: "Regularly cleanup un-used images and stopped containers"
  cron:
    name: "docker cleanup"
    hour: "*/12"
    minute: 0
    job: >
      /usr/local/bin/dd-cron-event
      "Cleanup docker images and containers"
      "echo y | docker system prune"
  become: "{{ user }}"

- name: Install the python docker library
  pip:
    name:
    - docker
    - docker-compose
    state: present

- name: "Install the ssl backports library"
  apt:
    name: python-backports.ssl-match-hostname
    state: present
  when: ansible_os_family == "Debian" and ansible_lsb['id'] == 'Raspbian'