- name: "Create sophro backup directory"
  file:
    path: "/home/{{ user }}/backups/sophro"
    state: directory
  become: yes
  become_user: "{{ user }}"

- name: "Schedule sophro backups"
  cron:
    name: "backup sophro"
    minute: "0"
    hour: "0"
    job: >
      dogwrap -n "Backup sophro web files"
      --submit_mode all
      -k $(grep apikey {{ user_home }}/.dogrc | cut -d= -f2 | sed "s/ //")
      "rsync -r --delete {{ user }}@51.254.120.74:{{ user_home }}/backups/ {{ user_home }}/backups/sophro"
  become: yes
  become_user: "{{ user }}"

- name: "Schedule the backup of the wallabag database"
  cron:
    name: "backup wallabag db"
    minute: "0"
    hour: "0"
    job: >
      dogwrap -n "Backup wallabag db"
      --submit_mode all
      -k $(grep apikey {{ user_home }}/.dogrc | cut -d= -f2 | sed 's/ //')
      "rsync -r --delete {{ user_home }}/wallabag/data/db/wallabag.sqlite {{ user }}@{{ home_domain }}:{{ user_home }}/backups/wallabag/wallabag.sqlite"
  become: yes
  become_user: "{{ user }}"
