- name: "Create backup directories"
  file:
    path: "/home/{{ user }}/backups/{{ item }}"
    state: directory
  become: yes
  become_user: "{{ user }}"
  with_items:
    - sophro

- name: "Schedule sophro backups"
  cron:
    name: "backup sophro"
    minute: "0"
    hour: "0"
    job: >
      /usr/local/bin/dd-cron-event
      "Backup sophro web files"
      "rsync -r --delete {{ user }}@51.254.120.74:{{ user_home }}/backups/ {{ user_home }}/backups/sophro"
    user: "{{ user }}"

- name: "Schedule the backup of the wallabag database"
  cron:
    name: "backup wallabag db"
    minute: "0"
    hour: "0"
    job: >
      /usr/local/bin/dd-cron-event
      "Backup wallabag db"
      "rsync -r {{ user_home }}/wallabag/data/db/wallabag.sqlite {{ user }}@{{ home_domain }}:{{ user_home }}/backups/wallabag/wallabag.sqlite"
    user: "{{ user }}"

- name: "Schedule the backup of the calibre metadata database"
  cron:
    name: "backup calibre db"
    minute: "0"
    hour: "0"
    job: >
      /usr/local/bin/dd-cron-event
      "Backup calibre metadata db"
      "rsync -r {{ user_home }}/calibre/books/metadata.db {{ user }}@{{ home_domain }}:{{ user_home }}/backups/calibre/metadata.db"
    user: "{{ user }}"


- name: "Schedule the backup of the calibre app database"
  cron:
    name: "backup calibre app db"
    minute: "0"
    hour: "0"
    job: >
      /usr/local/bin/dd-cron-event
      "Backup calibre db"
      "rsync -r {{ user_home }}/calibre/config/app.db {{ user }}@{{ home_domain }}:{{ user_home }}/backups/calibre/app.db"
    user: "{{ user }}"

- name: "Schedule the backup of the isso database"
  cron:
    name: "backup isso db"
    minute: "0"
    hour: "0"
    job: >
      /usr/local/bin/dd-cron-event
      "Backup isso db"
      "rsync -r {{ isso_home }}/db/comments.db {{ user }}@{{ home_domain }}:{{ user_home }}/backups/isso/comments.db"
    user: "{{ user }}"

- name: "Schedule the backup of the grand-cedre database"
  cron:
    name: "backup grand-cedre db"
    minute: "0"
    hour: "0"
    job: >
      /usr/local/bin/dd-cron-event
      "Backup grand-cedre db"
      "rsync -r {{ grand_cedre_home }}/data/data.db {{ user }}@{{ home_domain }}:{{ user_home }}/backups/grand-cedre/data.db"
    user: "{{ user }}"

- name: "Schedule the backup of radicale files"
  cron:
    name: "backup radicale files"
    minute: "0"
    hour: "0"
    job: >
      /usr/local/bin/dd-cron-event
      "Backup radicale files"
      "rsync -r {{ user_home }}/radicale {{ user }}@{{ home_domain }}:{{ user_home }}/backups/radicale"
    user: "{{ user }}"

- name: "Schedule nextcloud backups"
  cron:
    name: "backup nextcloud DB"
    minute: "0"
    hour: "0"
    job: >
      /usr/local/bin/dd-cron-event
      "Backup nextcloud db"
      "rsync -e \"ssh -i {{ user_home }}/.ssh/id_rsa\" {{ nextcloud_home }}/data/owncloud.db {{ user }}@{{ home_domain }}:{{ user_home }}/backups/nextcloud"
    user: "root"
