- name: "Update and upgrade packages"
  apt:
    update_cache: yes
    upgrade: dist

- name: "Install packages"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - htop
    - python-pip
    - python3
    - python3-pip
    - vim
    - docker.io

- name: "Add user to the docker group"
  user:
    name: "{{ user }}"
    uid: "{{ user_uid }}"
    groups: "{{ group }},sudo,docker"
    append: yes
    state: present

- name: "Regularly cleanup un-used images and stopped containers"
  cron:
    name: "docker cleanup"
    hour: "*/12"
    minute: 0
    job: "echo y | docker system prune"
  become: "{{ user }}"

- name: "Remove un-needed packages"
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - snap
    - lvm2
    - lxcfs

- pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - pip
    - docker-py
    - bcrypt
    - passlib

- name: "Setup motd"
  copy:
    src: motd
    dest: /etc/motd

- name: "Setup profile"
  copy:
    src: profile
    dest: "{{ user_home }}/.profile"
    owner: "{{ user }}"

- name: 'Set hostname'
  hostname:
    name: "{{ hostname }}"

- name: "Make hostname resolvable"
  lineinfile:
    path: /etc/hosts
    regexp: '127.0.0.1 localhost'
    line: "127.0.0.1 localhost {{ hostname }}"
    state: present

- name: "Setup user authorized keys"
  template:
    src: authorized_keys.j2
    dest: "{{ user_home }}/.ssh/authorized_keys"
    owner: "{{ user }}"
    group: "{{ group }}"
