- name: software-properties-common installed
  apt:
    name: software-properties-common
    state: latest

- name: certbot ppa added
  apt_repository:
    repo: 'ppa:certbot/certbot'

- name: certbot installed
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - certbot
    - python-certbot-nginx
