- include_tasks: Debian.yml
  when: ansible_distribution == 'Debian'

- include_tasks: Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: "Check whether port 443 is available to avoid that certbot fails and returns: 'Could not bind TCP port 443 because it is already in use by another process'"
  wait_for:
    port: 443
    state: stopped
    timeout: "{{ certbot_waitfor_port_seconds }}"
  when: certbot_create_certs

- name: certs created
  command: certbot certonly --standalone -d {{ item }} -m {{ certbot_mail_address }} --agree-tos --noninteractive --text
  args:
    creates: "{{ certbot_live_home }}/{{ item }}/fullchain.pem"
  when: certbot_create_certs
  with_items:
    - "{{ certbot_list_of_certs_to_create }}"

- name: renew certs
  cron:
    name: renewCertbotCerts
    user: root
    special_time: weekly
    job: "{{ certbot_renew_certs_job }}"
    state: present
    disabled: no
  when: certbot_renew_certs

- name: "Remove default certbot cron job"
  file:
    path: /etc/cron.d/certbot
    state: absent
