- name: "Update and upgrade packages"
  apt:
    update_cache: yes
    upgrade: dist

- name: "Install packages"
  apt:
    name:
    - htop
    - python3
    - python3-pip
    - python3-virtualenv
    - vim
    - tmux
    - zip
    state: present

- name: "Remove un-needed packages"
  apt:
    name:
    - snap
    - lvm2
    - lxcfs
    state: absent

- name: Allow pip to install packages
  file:
    path: /usr/lib/python3.11/EXTERNALLY-MANAGED
    state: absent

- name: "Install python packages"
  pip:
    name:
    - bcrypt
    - passlib
    - pyyaml>=6.0.0
    state: present
    extra_args: --break-system-packages

- name: "Setup motd"
  copy:
    src: motd
    dest: /etc/motd

- name: "Remove dynamic updates to the motd"
  shell: "chmod -x /etc/update-motd.d/*"

- name: "Setup profile"
  copy:
    src: profile
    dest: "{{ user_home }}/.profile"
    owner: "{{ user }}"

- name: 'Set hostname'
  hostname:
    name: "{{ hostname }}"

- name: "Make hostname resolvable"
  lineinfile:
    path: /etc/hosts
    regexp: '127.0.0.1 localhost'
    line: "127.0.0.1 localhost {{ hostname }}"
    state: present

- name: "Setup user authorized keys"
  template:
    src: authorized_keys.j2
    dest: "{{ user_home }}/.ssh/authorized_keys"
    owner: "{{ user }}"
    group: "{{ group }}"
