- name: "Create the jakett home config"
  file:
    path: "{{ jackett_home }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"

- name: "Run the jackett container"
  include_role:
    name: mhutter.docker-systemd-service
  vars:
    container_name: jackett
    container_image: "linuxserver/jackett:{{ jackett_version }}"
    container_docker_pull: no
    container_ports:
      - "{{ peers['gallifrey']['wireguard']['ip'] }}:{{ jackett_port }}:{{ jackett_port }}/tcp"
    container_env:
      PUID: "{{ user_uid | quote }}"
      PGID: "{{ user_gid | quote }}"
      TZ: "Europe/Paris"
    container_volumes:
      - "{{ jackett_home }}:/config"
    service_systemd_unit_options:
      After: "docker.service wg-quick@wg0.service"
      Requires: "docker.service wg-quick@wg0.service"

- name: "Backup the jackett config"
  cron:
    name: "Backup the jackett config"
    minute: "0"
    hour: "1"
    job: "{{ syno_rsync }} {{ jackett_home }}/Jackett/ServerConfig.json {{ user }}@{{ peers['chambonas']['wireguard']['ip'] }}:~/backups/jackett/ServerConfig.json"
    user: "{{ user }}"