- name: "Create the yarr directory"
  file:
    path: "{{ yarr_home }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group  }}"

- name: "Start the yarr container"
  docker_container:
    name: yarr
    image: "maskalicz/yarr:latest"
    state: started
    pull: yes
    published_ports:
      - "{{ yarr_host }}:{{ yarr_port }}:7070"
    restart_policy: unless-stopped
    volumes:
      - "{{ yarr_home }}:/data"

- name: "Copy yarr sites-available nginx conf"
  template:
    src: yarr.conf.j2
    dest: /etc/nginx/sites-available/yarr.conf
    owner: root
    group: root
  notify: "reload nginx"

- name: "Link yarr sites-enabled nginx conf"
  file:
    src: /etc/nginx/sites-available/yarr.conf
    dest: /etc/nginx/sites-enabled/yarr.conf
    state: link
  notify: "reload nginx"

- name: "Install rss parsing scripts"
  copy:
    src: "{{ item }}.py"
    dest: "/usr/local/bin/{{ item }}"
    group: git
    mode: 0775
  loop:
    - rssgen
    - rss_scrape_sharpmaps
    - rss_scrape_wmf_signpost
    - rss_scrape_wmfjobs

- name: "Schedule WMF jobs rss export"
  cron:
    name: "wmf jobs rss"
    minute: "0"
    hour: "4"
    job: >
      curl -s 'https://job-boards.greenhouse.io/wikimedia' |
      /usr/local/bin/rss_scrape_wmfjobs |
      rssgen --title 'WMF Jobs' --link '' --description 'P/T jobs at the WMF' > {{ page_web_dir }}/public/wmfjobs.rss
    user: git

- name: "Schedule sharpamps rss export"
  cron:
    name: "sharpmaps jobs rss"
    minute: "0"
    hour: "4"
    job: >
      curl -s "https://sharpmaps.com/" |
      /usr/local/bin/rss_scrape_sharpmaps |
      rssgen --title 'Sharpmaps' --link 'https://sharpmaps.com' --description 'Generate beautiful maps' > {{ page_web_dir }}/public/sharpmaps.rss
    user: git

- name: "Schedule wmg signpost rss export"
  cron:
    name: "wmf signpost rss"
    minute: "0"
    hour: "4"
    job: >
      curl -L -s "https://tools.wmflabs.org/mediawiki-feeds/feed.php?url=https%3A%2F%2Fen.wikipedia.org%2Fw%2F&category=Category%3AWikipedia+Signpost+single+page+RSS+feed&title=The+Signpost+(single-page)" |
      /usr/local/bin/rss_scrape_wmf_signpost |
      rssgen --title 'Wikimedia Signpost' --link 'https://en.wikipedia.org/wiki/Wikipedia:Wikipedia_Signpost' --description 'Wikimedia Signpost'> {{ page_web_dir }}/public/wmfsignpost.rss
    user: git
