- name: "Create backup directories"
  file:
    path: "{{ user_home }}/backups/{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
  with_items:
    - wallabag
    - isso
    - calibre
    - grand-cedre
    - radicale
    - paperless
    - sophro
    - sonarr
    - jackett
    - bazarr
    - fathom
