- name: "Update and upgrade packages"
  apt:
    update_cache: yes
    upgrade: dist

- name: "Install packages"
  apt:
    name:
    - htop
    - python-pip
    - vim
    state: present

- name: "Remove unwanted packages"
  apt:
    name:
    - lighttpd
    state: absent

- name: "Install python packages"
  pip:
    name:
    - pip
    - passlib
    - setuptools
    state: latest

- name: "Setup motd"
  copy:
    src: motd
    dest: /etc/motd

- name: "Setup profile"
  copy:
    src: profile
    dest: "{{ user_home }}/.profile"
    owner: "{{ user }}"

- name: 'Set hostname'
  hostname:
    name: "{{ hostname }}"

- name: "Make hostname resolvable"
  lineinfile:
    path: /etc/hosts
    regexp: '127.0.0.1 localhost'
    line: "127.0.0.1 localhost {{ hostname }}"
    state: present

- name: "Create /opt directory"
  file:
    path: "{{ opt_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"

- name: "Mount temporary directories as tmpfs to save the SD card"
  lineinfile:
    path: /etc/fstab
    line: "{{ item }}"
    regexp: "{{ item }}"
    state: present
  with_items:
    - "tmpfs /tmp tmpfs defaults,noatime,nosuid,size=50m 0 0"
    - "tmpfs /var/tmp tmpfs defaults,noatime,nosuid,size=20m 0 0"
    - "tmpfs /var/log tmpfs defaults,noatime,nosuid,mode=0755,size=10m 0 0"

- name: "Disable the pi user from sshing"
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "DenyUsers pi"
    state: present
  notify:
    - restart ssh
