- name: "Make sure that the directory containing the datadog socket exists"
  file:
    path: "/var/run/datadog"
    state: directory
    owner: dd-agent
    group: dd-agent
  notify: "restart datadog-agent"

- name: Install python libraries required by monitoring scripts
  pip:
    name:
    - ovh
    - beautifulsoup4
    - datadog
    state: present
    executable: pip3
    extra_args: --break-system-packages

- name: render monitoring scripts
  template:
    src: "monitor_{{ item }}"
    dest: "/etc/cron.hourly/monitor_{{ item }}"
    owner: root
    group: root
    mode: 0755
  loop:
  - blog
  - blog_comments
  - ovh
  - rain
  - enedis

