- name: Install the samba packages
  apt:
    name:
    - samba-common-bin
    - samba-common
    - smbclient
    - cifs-utils
    state: present

- name: Create the nas mountpoint hirearchy
  file:
    path: "{{ item }}"
    state: directory
    owner: "debian-transmission"
    group: "debian-transmission"
  loop:
  - "{{ nas_mount_point }}"
  - "{{ download_directory }}"

- name: Render the samba credentials configuration file
  template:
    src: "smb-{{ item }}.j2"
    dest: "{{ user_home }}/.smb-{{ item }}"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: "0600"
  loop:
  - transmission

- name: Auto mount the downloads samba volume
  lineinfile:
    path: /etc/fstab
    state: present
    regexp: '^//{{ peers["chambonas"]["internal_ip"] }}/downloads/transmission'
    line: "//{{ peers['chambonas']['internal_ip'] }}/downloads/transmission\t{{ download_directory }}\tcifs\tuid={{ transmission_uid }},gid={{ transmission_gid }},credentials={{ user_home }}/.smb-transmission,iocharset=utf8,vers=3.0,noperm 0 0"
