- name: "Create the sonarr home config"
  file:
    path: "{{ jackett_home }}"
    state: directory
    owner: debian-transmission
    group: debian-transmission

- name: "Run the jackett container"
  include_role:
    name: mhutter.docker-systemd-service
  vars:
    container_name: jackett
    container_image: lscr.io/linuxserver/jackett:latest
    # container_docker_pull: yes
    container_ports:
      - "{{ ansible_default_ipv4.address }}:{{ jackett_port }}:{{ jackett_port }}/tcp"
    container_env:
      PUID: "{{ transmission_uid | quote }}"
      PGID: "{{ transmission_gid | quote }}"
      TZ: "Europe/Paris"
    container_args: "--dns {{ ansible_default_ipv4.address }}" # use pi-hole to circumvent blocked domains
    container_volumes:
      - "{{ jackett_home }}:/config"
      - "{{ transmission_download_dir }}:/downloads"

- name: "Backup the jackett config"
  cron:
    name: "Backup the jackett config"
    minute: "0"
    hour: "1"
    job: "{{ syno_rsync }} {{ jackett_home }}/Jackett/ServerConfig.json {{ user }}@{{ syno_internal_ip }}:~/backups/jackett/ServerConfig.json"
    user: "{{ user }}"