- name: "Install the datadog python library"
  pip:
    name: datadog
    state: present
    version: "0.29.3"

- name: "Render the dogrc config file"
  template:
    src: dogrc.j2
    dest: "{{ user_home }}/.dogrc"
