- name: Install wireguard
  apt:
    update_cache: yes
    name: wireguard
    state: present

- name: Configure the wg0 wireguard interface
  template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    mode: '0600'
    owner: root
    group: root
  notify: "restart wg-quick@w0"

- name: "Enable wg-quick@wg0"
  service:
    name: wg-quick@wg0
    state: started
    enabled: yes
    daemon_reload: yes
  ignore_errors: yes  # if the interface is already up

- name: Configure the wg1 wireguard interface
  template:
    src: wg1.conf.j2
    dest: /etc/wireguard/wg1.conf
    mode: '0600'
    owner: root
    group: root
  notify: "restart wg-quick@w1"

- name: "Enable wg-quick@wg1"
  service:
    name: wg-quick@wg1
    state: started
    enabled: yes
    daemon_reload: yes
  ignore_errors: yes  # if the interface is already up

- name: "Ensure wg0 link is established"
  cron:
    name: "ping on wg0"
    job: "ping -c 1 {{ peers['chambonas']['wireguard']['ip'] }}"
    user: "{{ user }}"
