- name: Create the homer directory
  file:
    path: "{{ homer_home }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"

- name: Render and copy the homer configuration file
  template:
    src: config.yml.j2
    dest: "{{ homer_home }}/config.yml"
    owner: "{{ user }}"
    group: "{{ group }}"

- name: Run the homer docker container
  include_role:
    name: mhutter.docker-systemd-service
  vars:
    container_name: homer
    container_image: "b4bz/homer:{{ homer_version }}"
    container_docker_pull: yes
    container_ports:
      - "{{ ansible_default_ipv4.address }}:80:8080/tcp"
    container_volumes:
      - "{{ homer_home }}:/www/assets"