- name: "Create kresus user"
  user:
    name: "{{ kresus_user }}"
    state: present
    shell: /bin/false
    createhome: yes
    home: "{{ kresus_user_home }}"

- name: "Create kresus data directory"
  file:
    path: "{{ kresus_data_dir }}"
    state: directory
    owner: "{{ kresus_user }}"

- name: "Create kesus tmpfs mount point"
  file:
    path: "{{ kresus_tmpfs_mount }}"
    state: directory
    owner: "{{ kresus_user }}"

- name: "Mount the kresus tmpfs directory"
  mount:
    path: "{{ kresus_tmpfs_mount }}"
    src: tmpfs
    state: mounted
    fstype: tmpfs
    opts: "size=32M,uid={{ kresus_user }},gid=users"

- name: "Cron the tmps directory backup to support reboots"
  cron:
    name: "backup kresus tmpfs dir"
    minute: "*/5"
    user: kresus
    job: "/usr/bin/rsync -ar {{ kresus_tmpfs_mount }}/ {{ kresus_user_home }}/.kresus/"

- name: "Clone the kresus directory"
  git:
    repo: 'https://framagit.org/kresusapp/kresus/'
    dest: "{{ kresus_dir }}"
    clone: yes
    update: no
    version: "{{ kresus_tag }}"
  become: yes
  become_user: "{{ kresus_user }}"

- name: "Install npm dependencies"
  npm:
    path: "{{ kresus_dir }}"
  become: yes
  become_user: "{{ kresus_user }}"

- name: "Make kresus production files"
  make:
    chdir: "{{ kresus_dir }}"
    target: build
  environment:
    NODE_ENV: production
  become: yes
  become_user: "{{ kresus_user }}"
  ignore_errors: yes
  args:
    creates: "/home/kresus/kresus/bin/kresus.js"

- name: "Create kresus htpasswd file"
  htpasswd:
    path: /etc/nginx/conf/kresus.htpasswd
    state: present
    username: "{{ kresus_username }}"
    password: "{{ kresus_password }}"

- name: "Define kresus systemd service file"
  template:
    src: kresus-unit.conf.j2
    dest: "/etc/systemd/system/kresus.service"
  notify:
    - start kresus

- name: "Copy kresus sites-available nginx conf"
  template:
    src: kresus.conf.j2
    dest: /etc/nginx/sites-available/kresus.conf
    owner: root
    group: root
  notify: "reload nginx"

- name: "Link kresus sites-enabled nginx conf"
  file:
    src: /etc/nginx/sites-available/kresus.conf
    dest: /etc/nginx/sites-enabled/kresus.conf
    state: link
  notify: "reload nginx"