- name: Install transmission
  apt:
    name: transmission-daemon
    state: present

- name: Create the transmission download directory
  file:
    dest: "{{ transmission_download_dir }}"
    state: directory
    owner: "debian-transmission"
    group: "debian-transmission"

- name: "Tweak the systemd transmission service"
  template:
    src: transmission-daemon.service.j2
    dest: /lib/systemd/system/transmission-daemon.service
  notify:
    - systemctl daemon reload

- name: Tweak the default transmission config file
  template:
    src: transmission-settings.json.j2
    dest: /etc/transmission-daemon/settings.json
    owner: debian-transmission
    group: debian-transmission
    mode: '0644'
  notify:
    - reload transmission-daemon

- name: Setup the vpn routing table
  lineinfile:
    path: /etc/iproute2/rt_tables
    regexp: "{{ vpn_routing_table_id }}\tvpn"
    line: "{{ vpn_routing_table_id }}\tvpn"
    state: present

- name: Setup the vpn0 bridge
  template:
    src: vpn0.j2
    dest: /etc/network/interfaces.d/vpn0
  notify:
    - restart networking
    - reload transmission-daemon

- name: "Copy script ensuring the NAS download dir is mounted"
  template:
    src: ensure-nas-mounted.sh.j2
    dest: /root/ensure-nas-mounted.sh
    owner: root
    group: root
    mode: 0744

- name: "Regularly try to mount the NAS and restart transmission (for when the pi start faster than the NAS)"
  cron:
    name: "ensure NAS is mounted"
    minute: "*/5"
    job: /root/ensure-nas-mounted.sh
    user: root
