- name: Install transmission
  apt:
    name: transmission-daemon
    state: present

- name: Create the transmission download directory
  file:
    dest: "{{ transmission_download_dir }}"
    state: directory
    owner: "debian-transmission"
    group: "users"

- name: "Tweak the systemd transmission service"
  template:
    src: transmission-daemon.service.j2
    dest: /lib/systemd/system/transmission-daemon.service
  notify:
    - systemctl daemon reload

- name: Tweak the default transmission config file
  template:
    src: transmission-settings.json.j2
    dest: /etc/transmission-daemon/settings.json
    owner: debian-transmission
    group: debian-transmission
    mode: '0644'
  notify:
    - reload transmission-daemon

- name: Setup the vpn routing table
  lineinfile:
    path: /etc/iproute2/rt_tables
    regexp: "{{ vpn_routing_table_id }}\tvpn"
    line: "{{ vpn_routing_table_id }}\tvpn"
    state: present

- name: Setup the vpn0 bridge
  template:
    src: vpn0.j2
    dest: /etc/network/interfaces.d/vpn
  notify:
    - restart networking
    - reload transmission-daemon

- name: "Set high transmission download/upload limits during the day"
  cron:
    name: "set high transmission download/upload limits during the day"
    minute: "0"
    hour: "7"
    job: "/usr/bin/transmission-remote --downlimit 100 --uplimit 10"
  become: yes
  become_user: "{{ user }}"

- name: "Disable transmission download/upload limits during the night"
  cron:
    name: "disable transmission download/upload limits during the night"
    minute: "30"
    hour: "1"
    job: "/usr/bin/transmission-remote --no-downlimit --no-uplimit"
  become: yes
  become_user: "{{ user }}"
