---
- hosts: chambonas
  user: "{{ user }}"
  become: yes

  roles:
  - { role: ssh, tags: ['ssh'] }
  - { role: motd, tags: ['motd'] }
  - { role: webhooks, tags: ['webhooks'] }
  - { role: wireguard, tags: ['wireguard'] }
