---
- name: "start 5esheets"
  become: yes
  become_user: "{{ user }}"
  service:
    name: 5esheets
    state: started
    enabled: yes
    scope: user
    daemon_reload: yes
  environment:
    XDG_RUNTIME_DIR: "{{ user_xdg_runtime_dir }}"
