---
- name: "Install node"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - nodejs
    - npm

- name: "Create link nodejs->node"
  file:
    src: /usr/bin/nodejs
    dest: /usr/bin/node
    state: link

- name: "Install lounge"
  npm:
    name: thelounge
    global: yes
    state: present

- name: "Create systemd service for lounge"
  template:
    src: lounge-unit.conf.j2
    dest: "{{ user_systemd_dir }}/lounge.service"
  notify:
    - start lounge

- name: "Create lounge config dir"
  file:
    name: "{{ lounge_home }}"
    state: directory
  become: yes
  become_user: "{{ user }}"

- name: "Create lounge user dir"
  file:
    name: "{{ lounge_home }}/users"
    state: directory
  become: yes
  become_user: "{{ user }}"

- name: "Copy lounge config file"
  template:
    src: lounge-config.js.j2
    dest: "{{ lounge_home }}/config.js"
  become: yes
  become_user: "{{ user }}"
  notify:
    - start lounge

- name: "Copy lounge user config"
  template:
    src: balto.json.j2
    dest: "{{ lounge_home }}/users/balto.json"
  become: yes
  become_user: "{{ user }}"
  notify:
    - start lounge

- name: "Copy lounge sites-available nginx conf"
  template:
    src: lounge.conf.j2
    dest: /etc/nginx/sites-available/lounge.conf
    owner: root
    group: root
  notify: "reload nginx"

- name: "Link lounge sites-enabled nginx conf"
  file:
    src: /etc/nginx/sites-available/lounge.conf
    dest: /etc/nginx/sites-enabled/lounge.conf
    state: link
  notify: "reload nginx"
