- name: "Unarchive the nodejs distribution"
  unarchive:
    remote_src: true
    src: "https://nodejs.org/dist/v{{ node_version }}/node-v{{ node_version }}-linux-{{ ansible_architecture }}.tar.xz"
    dest: "{{ opt_dir }}"
    creates: "{{ opt_dir }}/node-v{{ node_version }}-linux-{{ ansible_architecture }}/bin/node"

- name: "Link the node binary into the path"
  file:
    src: "{{ opt_dir }}/node-v{{ node_version }}-linux-{{ ansible_architecture }}/bin/node"
    dest: /usr/local/bin/node
    state: link

- name: "Link the npm binary into the path"
  file:
    src: "{{ opt_dir }}/node-v{{ node_version }}-linux-{{ ansible_architecture }}/bin/npm"
    dest: /usr/local/bin/npm
    state: link

- name: "Install yarn"
  npm:
    name: yarn
    global: yes

- name: "Link the yarn binary into the path"
  file:
    src: "{{ opt_dir }}/node-v{{ node_version }}-linux-{{ ansible_architecture }}/bin/yarn"
    dest: /usr/local/bin/yarn
    state: link