- name: "Create martial user"
  user:
    name: "{{ martial_user }}"
    uid: "{{ martial_uid }}"
    groups: "users"
    append: yes
    state: present
    shell: /bin/bash
    createhome: yes
    home: "{{ martial_home }}"

- name: "Create martial ssh directory"
  file:
    dest: "{{ martial_home }}/.ssh"
    state: directory
    owner: "{{ martial_user }}"

- name: "Create martial volume"
  command: "fallocate -l {{ martial_volume_size }} {{ martial_volume }}"
  args:
    creates: "{{ martial_volume }}"

- name: "Create martial loop device"
  command: "losetup {{ martial_loop_device }} {{ martial_volume }}"
  args:
    creates: "{{ martial_loop_device }}"

- name: "Create martial web directory"
  file:
    path: "{{ martial_web_dir }}"
    state: directory
    owner: "{{ martial_uid }}"
    group: www-data

- name: Auto mount the martial data file
  ansible.posix.mount:
    path: "{{ martial_web_dir }}"
    src: "{{ martial_loop_device }}"
    fstype: ext4
    opts: defaults
    state: present

- name: "Copy martial sites-available nginx conf"
  template:
    src: martial.conf.j2
    dest: /etc/nginx/sites-available/martial.conf
    owner: root
    group: root
  notify: "reload nginx"

- name: "Link martial sites-enabled nginx conf"
  file:
    src: /etc/nginx/sites-available/martial.conf
    dest: /etc/nginx/sites-enabled/martial.conf
    state: link
  notify: "reload nginx"

- name: "Copy martial's SSH public key"
  template:
    src: authorized_keys.j2
    dest: "/home/{{ martial_user }}/.ssh/authorized_keys"
    owner: "{{ martial_user }}"
    group: users
    mode: "0644"
