- name: "Create the sonarr home config"
  file:
    path: "{{ sonarr_home }}"
    state: directory
    owner: debian-transmission
    group: debian-transmission

- name: "Run the sonarr container"
  include_role:
    name: mhutter.docker-systemd-service
  vars:
    container_name: sonarr
    container_image: lscr.io/linuxserver/sonarr:latest
    container_docker_pull: yes
    container_ports:
      - "{{ ansible_default_ipv4.address }}:{{ sonarr_port }}:{{ sonarr_port }}/tcp"
    container_env:
      PUID: "{{ transmission_uid | quote }}"
      PGID: "{{ transmission_gid | quote }}"
      TZ: "Europe/Paris"
    container_volumes:
      - "{{ sonarr_home }}:/config"
      - "{{ sonarr_series_dir }}:/tv"
      - "{{ transmission_download_dir }}:/downloads"

- name: "Backup the sonarr database"
  cron:
    name: "Backup the sonarr database"
    minute: "0"
    hour: "1"
    job: "{{ syno_rsync }} {{ sonarr_home }}/sonarr.db {{ user }}@{{ syno_internal_ip }}:~/backups/sonarr/sonarr.db"
    user: "{{ user }}"
