#!/usr/bin/env python3

import requests

from bs4 import BeautifulSoup
from datadog.dogstatsd import DogStatsd

statsd = DogStatsd(socket_path="{{ datadog_config['dogstatsd_socket'] }}")

RAIN_VOLUME_URLS = {
    "chaulet": "https://www.rdbrmc.com/hydroreel2/station.php?codestation=1086",
    "gravieres": "https://www.rdbrmc.com/hydroreel2/station.php?codestation=514",
    "villefort": "https://www.rdbrmc.com/hydroreel2/station.php?codestation=761",
}


def monitor_rain_volume(station_name):
    html = requests.get(RAIN_VOLUME_URLS[station_name]).text
    soup = BeautifulSoup(html, features="html.parser")
    h5_index = 1 if station_name == "villefort" else 3
    rain_level_h5 = soup.find_all("h5")[h5_index].text
    rain_level = float(rain_level_h5.split("dernier cumul horaire ")[1].split(" ")[0])
    statsd.gauge(
        "weather.rain.hourly", tags=[f"station:{station_name}"], value=rain_level
    )


def main():
    monitor_rain_volume("chaulet")
    monitor_rain_volume("gravieres")
    monitor_rain_volume("villefort")


if __name__ == "__main__":
    main()
