#!/usr/bin/env python3

import requests

from datadog.dogstatsd import DogStatsd


statsd = DogStatsd(socket_path="/var/run/datadog/datadog-agent.socket")

session = requests.Session()
session.headers.update({"api-key": "{{ devto_api_key }}"})

for article in session.get("https://dev.to/api/articles/me").json():
    clean_slug = "-".join(article["slug"].split("-")[:-1])
    tags = ["campaign:essential-tools", f"article:{clean_slug}"]
    statsd.gauge("devto.audience.views", value=article["page_views_count"], tags=tags)
    statsd.gauge(
        "devto.audience.likes", value=article["positive_reactions_count"], tags=tags
    )
    statsd.gauge("devto.audience.comments", value=article["comments_count"], tags=tags)
