#!/usr/bin/env python3

import sqlite3

from datadog.dogstatsd import DogStatsd


statsd = DogStatsd(socket_path='/var/run/datadog/datadog-agent.socket')
conn = sqlite3.connect('/mnt/data/nextcloud/data/owncloud.db')

c = conn.cursor()

query = """
select
    m.user_id,
    f.size
from
    oc_filecache f,
    oc_storages s,
    oc_mounts m
where
    s.numeric_id=m.storage_id and
    f.storage=m.storage_id and
    f.path='files'
group by
    m.user_id;
"""
res = c.execute(query)

for user, total_used_bytes in res:
    statsd.gauge(
        'nextcloud.storage.s3',
        value=total_used_bytes,
        tags=['user:%s' % (user)])
