- name: "Install necessary apt-packages"
  apt:
    name: python3-venv
    state: present

- name: "Create the project directory"
  file:
    path: "{{ user_home }}/notion"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"

- name: "Install python dependencies in a virtualenv"
  pip:
    name: notion
    state: present
    virtualenv: "{{ user_home }}/notion/.env"
    virtualenv_command: "/usr/bin/python3 -m venv"

- name: "Render the script"
  template:
    src: report_cesu.py.j2
    dest: "{{ user_home }}/notion/report_cesu.py"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: "0755"

- name: "Compute how many hours to report to CESU and export the result to Notion every month"
  cron:
    name: "Compute how many hours to report to CESU and export the result to Notion"
    minute: "1"
    hour: "0"
    day: "1"
    job: >
      /usr/local/bin/dd-cron-event
      "Export CESU hours to Notion"
      "{{ user_home }}/notion/report_cesu.py --year $(date --date='-1 month' +\%Y) --month $(date --date='-1 month' +\%m)"
    user: "{{ user }}"
