---
roles:
  - name: datadog.datadog
    version: 4.13.0
  - name: geerlingguy.certbot
    version: 5.0.1
  - name: mhutter.docker-systemd-service
    version: v2.8.0
    version: 1.2.1

collections:
  - name: community.general
    version: 5.5.0
  - name: geerlingguy.mac
    version: 2.0.0
  - name: community.docker
    version: 4.3.1
