- name: "Update and upgrade packages"
  apt:
    update_cache: yes
    upgrade: dist

- name: "Install packages"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - htop
    - python-pip
    - vim

- name: "Remove un-needed packages"
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - snap
    - lvm2
    - lxcfs

- pip:
    name: pip
    state: latest

- name: "Setup motd"
  copy:
    src: motd
    dest: /etc/motd

- name: "Setup profile"
  copy:
    src: profile
    dest: "{{ user_home }}/.profile"
    owner: "{{ user }}"

- name: 'Set hostname'
  hostname:
    name: "{{ hostname }}"

- name: "Make hostname resolvable"
  lineinfile:
    path: /etc/hosts
    regexp: '127.0.0.1 localhost'
    line: "127.0.0.1 localhost {{ hostname }}"
    state: present
