- name: "Install user dbus session"
  apt:
    name: "dbus-user-session"
    state: present

- name: "Create user systemd service directory"
  file:
    state: directory
    path: "{{ user_systemd_dir }}"
    owner: "{{ user }}"
    group: "{{ group }}"

- name: "Allow {{ user }} to run lingering systemd services"
  command: "loginctl enable-linger {{ user }}"
  args:
    creates: "/var/lib/systemd/linger/{{ user }}"
