- name: Install the samba packages
  apt:
    name:
    - samba-common-bin
    - samba-common
    - smbclient
    - cifs-utils
    state: present

- name: Create the nas mountpoint hirearchy
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
  with_items:
  - "{{ nas_mount_point }}"
  - "{{ download_directory }}"


- name: Render the samba credentials configuration file
  template:
    src: smb.j2
    dest: "{{ user_home }}/.smb"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: "0600"

- name: Auto mount the downloads samba volume
  lineinfile:
    path: /etc/fstab
    state: present
    regexp: '^//192.168.100.131/downloads/transmission'
    line: "//192.168.100.131/downloads/transmission\t{{ download_directory }}\tcifs\tuid=0,credentials={{ user_home }}/.smb,iocharset=utf8,vers=3.0,noperm 0 0"
