- name: "Create user group"
  group:
    name: "{{ group }}"
    state: present

- name: "Create user"
  user:
    name: "{{ user }}"
    uid: "{{ user_uid }}"
    groups: "{{ group }},sudo"
    append: yes
    state: present
    shell: /bin/bash
    createhome: yes
    home: "{{ user_home }}"
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa

- name: "Add the user to the sudoers"
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%{{ user }} ALL=\(ALL\) NOPASSWD: ALL$'
    line: "%{{ user }} ALL=(ALL) NOPASSWD: ALL"

- name: "Setup user authorized keys"
  template:
    src: authorized_keys.j2
    dest: "{{ user_home }}/.ssh/authorized_keys"
    owner: "{{ user }}"
    group: "{{ group }}"

- name: "Remove any ssh authorized_keys"
  file:
    path: /home/ubuntu/.ssh/authorized_keys
    state: absent

- name: "Create external disks mountpoints"
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
  with_items:
  - /mnt/data

- name: "Mount external disks"
  lineinfile:
    path: /etc/fstab
    line: "{{ item }}"
    regexp: "{{ item }}"
    state: present
  with_items:
  - "UUID=ef993b56-c230-4595-a9a9-185ca207f5e6 /mnt/data ext4 defaults 0 0
