- name: Clone the sclack repository
  git:
    repo: https://github.com/haskellcamargo/sclack.git
    dest: "{{ slack_home }}"
    version: master

- name: Create slack virtualenv
  command: "virtualenv -p python3 {{ slack_home }}/.env"
  args:
    creates: "{{ slack_home }}/.env"

- name: Install python dependencies
  pip:
    requirements: requirements.txt
    chdir: "{{ slack_home }}"
    virtualenv: "{{ slack_home }}/.env"

- name: Render the sclack config file
  template:
    src: sclack.j2
    dest: "{{ user_home }}/.sclack"
    owner: "{{ user }}"
    group: "{{ group }}"

- name: "Create systemd service for slack"
  template:
    src: slack-unit.conf.j2
    dest: "{{ user_systemd_dir }}/slack.service"
  notify:
    - start slack