- name: "Start the 5esheets container"
  docker_container:
    name: 5esheets
    image: "ghcr.io/brouberol/5esheets:main"
    state: started
    published_ports:
      - "127.0.0.1:{{ _5esheets_port }}:8000"
    restart_policy: unless-stopped
    pull: yes
    volumes:
      - "{{ _5esheets_home }}/db:/usr/src/app/db"

- name: "Copy 5esheets sites-available nginx conf"
  template:
    src: 5esheets.conf.j2
    dest: /etc/nginx/sites-available/5esheets.conf
    owner: root
    group: root
  notify: "reload nginx"

- name: "Link 5esheets sites-enabled nginx conf"
  file:
    src: /etc/nginx/sites-available/5esheets.conf
    dest: /etc/nginx/sites-enabled/5esheets.conf
    state: link
  notify: "reload nginx"

- name: "Schedule the backup of the 5esheets database"
  cron:
    name: "backup 5esheets db"
    minute: "0"
    hour: "0"
    job: >
      /usr/local/bin/dd-cron-event
      "Backup 5esheets db"
      "{{ syno_rsync }} -r {{ _5esheets_home }}/db/5esheets.db syno:{{ syno_user_home }}/backups/5esheets/5esheets.db"
    user: "{{ user }}"