---
- hosts: gallifrey
  user: "{{ user }}"
  become: yes
  become_method: sudo

  roles:
  - { role: setup, tags: ['setup'] }
  - { role: docker, tags: ['docker'] }
  - { role: setup-user-systemd, tags: ['setup-user-systemd'] }
  - { role: security, tags: ['security'] }
  - { role: duo, tags: ['duo'] }
  - { role: git, tags: ['git'] }
  - { role: datadog-agent, tags: ['datadog-agent', 'datadog'] }
  - { role: datadogpy, tags: ['datadogpy', 'datadog'] }
  - { role: nginx, tags: ['nginx', 'web'] }
  - { role: certbot, tags: ['certbot', 'web'] }
  - { role: page, tags: ['page', 'web'] }
  - { role: blog, tags: ['blog', 'web'] }
  - { role: myip, tags: ['myip', 'services'] }
  - { role: fathom, tags: ['fathom', 'services'] }
  - { role: lounge, tags: ['lounge', 'web', 'services'] }
  - { role: wallabag, tags: ['wallabag', 'web', 'services'] }
  - { role: radicale, tags: ['radicale', 'web', 'services'] }
  - { role: backups, tags: ['backups'] }
  - { role: pastebin, tags: ['pastebin'] }
  - { role: isso, tags: ['isso'] }
  - { role: calibre, tags: ['calibre'] }

  post_tasks:
  - include_vars:
      file: roles/common/datadog-agent/vars/main.yml

  - name: "Send datadog event"
    datadog_event:
      api_key: "{{ datadog_api_key }}"
      app_key: "{{ datadog_app_key }}"
      alert_type: success
      aggregation_key: ansible-deploy
      title: "Successful deployment"
      text: "The deployment playbook ran successfully"
    delegate_to: localhost
    become: no
