---
- hosts: pi
  user: "{{ user }}"
  become: yes
  become_method: sudo

  roles:
  - { role: pi-setup, tags: ['setup'] }
  - { role: inputrc, tags: ['setup', 'inputrc'] }
  - { role: docker, tags: ['docker'] }
  - { role: geerlingguy.certbot, tags: ['certbot'] }
  - { role: pi-datadog-agent, tags: ['datadog-agent', 'datadog'] }
  - { role: datadog.datadog, tags: ['datadog-agent', 'datadog'] }
  - { role: datadogpy, tags: ['datadogpy', 'datadog'] }
  - { role: nginx, tags: ['nginx', 'web'] }
  - { role: cloudflared, tags: ['cloudflared', 'dns'] }
  - { role: pihole, tags: ['pihole', 'dns'] }
  - { role: wireguard, tags: ['wireguard'] }
  - { role: samba, tags: ['samba'] }
  - { role: transmission, tags: ['transmission'] }
  - { role: notion, tags: ['notion'] }
  - { role: monitoring, tags: ['monitoring'] }
  - { role: homer, tags: ['homer'] }
  - { role: sonarr, tags: ['sonarr'] }
  - { role: jackett, tags: ['jackett'] }
  - { role: bazarr, tags: ['bazarr'] }
