---
- hosts: pistou
  user: "{{ user }}"
  become: yes
  become_method: sudo

  roles:
  # - { role: pi-setup, tags: ['setup'] }
  # - { role: layereight.wifi, tags: ['wifi'] }
  # - { role: inputrc, tags: ['setup', 'inputrc'] }
  # - { role: docker, tags: ['docker'] }
  - { role: samba, tags: ['samba'] }
  - { role: radarr, tags: ['radarr'] }

  handlers:
  - name: restart ssh
    ansible.builtin.service:
      name: ssh
      state: restarted