---
- hosts: sophro
  user: "{{ user }}"
  become: yes
  become_method: sudo

  roles:
  - { role: setup, tags: ['setup'] }
  - { role: security, tags: ['security'] }
  - { role: datadog.datadog, tags: ['datadog-agent', 'datadog'] }
  - { role: datadogpy, tags: ['datadogpy', 'datadog'] }
  - { role: nginx, tags: ['nginx', 'web'] }
  - { role: geerlingguy.certbot, tags: ['certbot', 'web'] }
  - { role: sophro-www, tags: ['sophro-www'] }

  post_tasks:
  - include_vars:
      file: roles/common/datadog-agent/vars/main.yml

  - name: "Send datadog event"
    datadog_event:
      api_key: "{{ datadog_api_key }}"
      app_key: "{{ datadog_app_key }}"
      alert_type: success
      aggregation_key: ansible-deploy
      title: "Successful deployment"
      text: "The deployment playbook ran successfully"
    delegate_to: localhost
    become: no
