- name: "Install weboob dependencies"
  apt:
    name:
    - git
    - python-dev
    - libffi-dev
    - libxml2-dev
    - libxslt-dev
    - libyaml-dev
    - libtiff-dev
    - libjpeg-dev
    - zlib1g-dev
    - libfreetype6-dev
    - libwebp-dev
    - build-essential
    - gcc
    - g++
    - wget
    - python-imaging
    - python-lxml
    - python-requests
    - python-unidecode
    state: present

- name: "Clone the weboob repository"
  git:
    repo: 'https://git.weboob.org/weboob/devel/'
    dest: "{{ weboob_dir }}"
    clone: yes
    update: no
    version: "1.5"

- name: "Install weboob from source"
  pip:
    chdir: "{{ weboob_dir }}"
    name: .

