- name: "Install weboob dependencies"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - git
  - python-dev
  - libffi-dev
  - libxml2-dev
  - libxslt-dev
  - libyaml-dev
  - libtiff-dev
  - libjpeg-dev
  - zlib1g-dev
  - libfreetype6-dev
  - libwebp-dev
  - build-essential
  - gcc
  - g++
  - wget
  - python-imaging
  - python-lxml

- name: "Clone the weboob repository"
  git:
    repo: 'https://git.weboob.org/weboob/devel/'
    dest: "{{ weboob_dir }}"
    clone: yes
    update: no

- name: "Install weboob from source"
  pip:
    chdir: "{{ weboob_dir }}"
    extra_args: --user
    name: .

