- name: "Create pastebin directory"
  file:
    path: "{{ pastebin_home }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"

- name: "Download pastebin"
  unarchive:
    src: "https://github.com/w4/bin/releases/download/v{{ pastebin_version }}/bin-v{{ pastebin_version }}-x86_64-unknown-linux-gnu.tar.gz"
    dest: "{{ pastebin_home }}"
    remote_src: yes
    creates: "{{ pastebin_home }}/bin"

- name: "Define pastebin systemd service file"
  template:
    src: pastebin-unit.conf.j2
    dest: "{{ user_systemd_dir }}/pastebin.service"
    owner: "{{ user }}"
    group: "{{ group }}"
  notify:
    - start pastebin

- name: "Copy pastebin sites-available nginx conf"
  template:
    src: pastebin-nginx.conf.j2
    dest: /etc/nginx/sites-available/pastebin.conf
    owner: root
    group: root
  notify: "reload nginx"

- name: "Link pastebin sites-enabled nginx conf"
  file:
    src: /etc/nginx/sites-available/pastebin.conf
    dest: /etc/nginx/sites-enabled/pastebin.conf
    state: link
  notify: "reload nginx"
