- name: "Create backup directories"
  file:
    path: "{{ user_home }}/backups/{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
  loop:
    - 5esheets
    - bazarr
    - calibre
    - fathom
    - grand-cedre
    - isso
    - jackett
    - paperless
    - radarr
    - radicale
    - sonarr
    - sophro
    - wallabag
    - silverbullet
    - yarr
    - authelia
    - martial
