---

- name: "Create the /etc/pihole directory"
  file:
    state: directory
    path: /etc/pihole
    owner: root
    group: root
  become: yes

- name: Run the pihole docker container
  include_role:
    name: mhutter.docker-systemd-service
  vars:
    container_name: pihole
    container_image: pihole/pihole:{{ pihole_tag }}
    container_volumes:
      - "/etc/pihole:/etc/pihole/"
    container_args: "--log-driver none"
    container_env:
      TZ: UTC
      WEBPASSWORD: "{{ pihole_web_password }}"
      PIHOLE_DNS_: "127.0.0.1#{{ cloudflared_port }}" # for when net=host
      FTLCONF_LOCAL_IPV4: "{{ peers['pi']['internal_ip'] }}"
      WEB_BIND_ADDR: "{{ peers['pi']['internal_ip'] }}"
      PIHOLE_UID: "1000"
      PIHOLE_GID: "1000"
      MAXDBDAYS: "30" # number of days of data to keep in the sqlite DB
