---

- name: "Create the /etc/pihole directory"
  file:
    state: directory
    path: /etc/pihole
    owner: root
    group: root
  become: yes

- name: Run the pihole docker container
  include_role:
    name: mhutter.docker-systemd-service
  vars:
    container_name: pihole
    container_image: pihole/pihole:{{ pihole_tag }}
    container_volumes:
      - "/etc/pihole:/etc/pihole/"
    container_args: "--log-driver none"
    container_env:
      TZ: UTC
      FTLCONF_webserver_api_password: "{{ pihole_web_password }}"
      FTLCONF_dns_upstreams: "127.0.0.1#{{ cloudflared_port }}"
      FTLCONF_dns_dnssec: "false"
      FTLCONF_webserver_port: "80"
      FTLCONF_database_maxDBdays: "30"
      PIHOLE_UID: "1000"
      PIHOLE_GID: "1000"
