- name: Install python libraries required by monitoring scripts
  pip:
    name:
    - praw
    - mailchimp3
    - ovh
    - beautifulsoup4
    - datadog
    state: present
    executable: pip3

- name: render monitoring scripts
  template:
    src: "monitor_{{ item }}"
    dest: "/etc/cron.hourly/monitor_{{ item }}"
    owner: root
    group: root
    mode: 0755
  with_items:
  - blog
  - blog_comments
  - devto
  - lobsters
  - mailchimp
  - ovh
  - reddit
  - rain

- name: "Copy the river level monitoring script to a bindir"
  copy:
    src: files/monitor_rivers
    dest: /usr/local/bin/monitor_rivers
    mode: 0755
    owner: root
    group: root

- name: "Monitor river level at different stations"
  cron:
    name: "monitor rivers"
    minute: "*/5"
    job: /usr/local/bin/monitor_rivers
    user: "{{ user }}"

- name: "Monitor fioul price every day"
  copy:
    src: monitor_fioul
    dest: /etc/cron.daily/monitor_fioul
    owner: root
    group: root
    mode: 0755
