- name: render monitoring scripts
  template:
    src: "{{ item }}"
    dest: "/etc/cron.hourly/{{ item }}"
    owner: root
    group: root
    mode: 0755
  with_items:
  - monitor_blog
  - monitor_blog_comments
  - monitor_devto
  - monitor_lobsters
  - monitor_mailchimp
  - monitor_nextcloud
  - monitor_reddit