- name: Install python libraries required by monitoring scripts
  pip:
    name:
    - praw
    - mailchimp3
    - ovh
    - beautifulsoup4
    state: present
    executable: pip3

- name: render monitoring scripts
  template:
    src: "{{ item }}"
    dest: "/etc/cron.hourly/{{ item }}"
    owner: root
    group: root
    mode: 0755
  with_items:
  - monitor_blog
  - monitor_blog_comments
  - monitor_devto
  - monitor_lobsters
  - monitor_mailchimp
  - monitor_scaleway
  - monitor_ovh
  - monitor_reddit
  - monitor_rain

- name: "Copy the river level monitoring script to a bindir"
  copy:
    src: files/monitor_rivers
    dest: /usr/local/bin/monitor_rivers
    mode: 0755
    owner: root
    group: root

- name: "Monitor river level at different stations"
  cron:
    name: "monitor rivers"
    minute: "*/5"
    job: /usr/local/bin/monitor_rivers
    user: "{{ user }}"
