- name: restart networking service
  service:
    name: networking
    state: restarted
  listen: "restart networking"

- name: reload transmission-daemon service
  service:
    name: transmission-daemon
    state: reloaded
  listen: "reload transmission-daemon"

- name: systemctl daemon reload
  systemd:
    daemon_reload: yes
  listen: "systemctl daemon reload"