#!/usr/bin/env python3

import requests

from enum import Enum
from bs4 import BeautifulSoup
from datadog.dogstatsd import DogStatsd

statsd = DogStatsd(socket_path="/var/run/datadog/datadog-agent.socket")

VIGICRUE_STATION_IDS = {
    "chaulet": "V504881301",
    "gravieres": "V504503001",
    "saintines": "H751301001",
}

RIVER_TO_TERRITORY_ID = {
    "chassezac": "20",
    "oise": "5",
}

RIVER_TO_CSS_ID = {
    "chassezac": "dropdownMenu4",
    "oise": "dropdownMenu5",
}


class AlertLevel(Enum):
    GREEN = 0
    YELLOW = 1
    ORANGE = 2
    RED = 3


def monitor_alert_level(river_name):
    url = "https://www.vigicrues.gouv.fr/niv2-bassin.php?CdEntVigiCru=%s" % (
        RIVER_TO_TERRITORY_ID[river_name]
    )
    html = requests.get(url).text
    soup = BeautifulSoup(html, features="html.parser")
    alert_text = soup.find("button", id=RIVER_TO_CSS_ID[river_name]).parent.p.text
    alert_level = None
    if "Vert" in alert_text:
        alert_level = AlertLevel.GREEN
    elif "Jaune" in alert_text:
        alert_level = AlertLevel.YELLOW
    elif "Orange" in alert_text:
        alert_level = AlertLevel.ORANGE
    elif "Rouge" in alert_text:
        alert_level = AlertLevel.RED

    if alert_level is not None:
        statsd.gauge(
            "river.alert_level",
            tags=["river:%s" % (river_name)],
            value=alert_level.value,
        )


def monitor_river(river_name, station_name):
    url = (
        "https://www.vigicrues.gouv.fr/services/observations.json/?CdStationHydro=%s&FormatDate=iso"
        % (VIGICRUE_STATION_IDS[station_name])
    )
    data = requests.get(url).json()
    datapoint = data["Serie"]["ObssHydro"][-1]
    value = datapoint["ResObsHydro"]
    statsd.gauge(
        "river.level",
        value=value,
        tags=[f"station:{station_name}", f"river:{river_name}"],
    )


def main():
    monitor_alert_level("chassezac")
    monitor_alert_level("oise")
    monitor_river("chassezac", "chaulet")
    monitor_river("chassezac", "gravieres")
    monitor_river("oise", "saintines")


if __name__ == "__main__":
    main()
