---

- name: "Create the /etc/pihole directory"
  file:
    state: directory
    path: /etc/pihole
    owner: root
    group: root
  become: yes

- name: Run the pihole docker container
  docker_container:
    name: pihole
    image: pihole/pihole:latest
    state: started
    published_ports:
      - 127.0.0.1:53:53/udp
      - "{{ ansible_default_ipv4.address }}:53:53/udp"
      - 0.0.0.0:67:67/udp
      - 0.0.0.0:80:80/tcp
      - 0.0.0.0:443:443/tcp
    volumes:
      - "/etc/pihole:/etc/pihole/"
    restart_policy: unless-stopped
    dns_servers:
      - "127.0.0.1"
      - "1.1.1.1"
    env:
      TZ: UTC
      WEBPASSWORD: "{{ pihole_web_password }}"
      DNS1: "1.1.1.1"
      DNS2: "1.0.0.1"
      DNSSEC: "true"
      ServerIP: "{{ ansible_default_ipv4.address }}"
