---

- name: "Create the /etc/pihole directory"
  file:
    state: directory
    path: /etc/pihole
    owner: root
    group: root
  become: yes

- name: Run the pihole docker container
  include_role:
    name: mhutter.docker-systemd-service
  vars:
    container_name: pihole
    container_image: pihole/pihole:latest
    container_docker_pull: yes
    container_ports:
      - 127.0.0.1:53:53/udp
      - "{{ ansible_default_ipv4.address }}:53:53/udp"
      - 0.0.0.0:67:67/udp
      - "0.0.0.0:{{ pihole_admin_port }}:80/tcp"
      - 0.0.0.0:443:443/tcp
    container_volumes:
      - "/etc/pihole:/etc/pihole/"
    container_args: "--dns 127.0.0.1 --dns 1.1.1.1 --log-driver none"
    container_env:
      TZ: UTC
      WEBPASSWORD: "{{ pihole_web_password }}"
      DNS1: "1.1.1.1"
      DNS2: "1.0.0.1"
      DNSSEC: "true"
      ServerIP: "{{ ansible_default_ipv4.address }}"
